# Generated by Django 2.0.3 on 2018-03-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_exp',
            field=models.DateTimeField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Name'),
        ),
    ]
