# Generated by Django 2.0.3 on 2018-03-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180320_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_exp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
