# Generated by Django 2.0.3 on 2018-03-25 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180326_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=64, verbose_name='Client IP Address')),
                ('date_visit', models.DateTimeField(blank=True, null=True, verbose_name='Visit Date')),
                ('browser_agent', models.CharField(max_length=300, verbose_name='Browser Agent')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
