# Generated by Django 2.0.3 on 2018-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlog',
            name='browser_agent',
            field=models.CharField(max_length=400, verbose_name='Browser Agent'),
        ),
    ]
