# Generated by Django 2.0.3 on 2018-03-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180326_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postlogs', to='post.Post'),
        ),
    ]
