# Generated by Django 2.0.3 on 2018-03-25 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20180326_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
